# Generated by Django 5.1 on 2024-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlogmodel',
            name='use_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未使用'), (2, '已过期'), (1, '已使用')], default=0, null=True, verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='couponmodels',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(1, '指定方向专业'), (0, '通用类型'), (3, '指定课程'), (2, '指定课程分类')], default=0, verbose_name='优惠券类型'),
        ),
    ]
