# Generated by Django 5.1 on 2024-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_couponlogmodel_use_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlogmodel',
            name='use_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, null=True, verbose_name='使用状态'),
        ),
    ]
