# Generated by Django 5.1 on 2024-09-10 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_couponlogmodel_use_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlogmodel',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='to_coupon', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='couponmodels',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(0, '通用类型'), (1, '指定方向专业'), (2, '指定课程分类'), (3, '指定课程')], default=0, verbose_name='优惠券类型'),
        ),
    ]
