# Generated by Django 5.1 on 2024-09-02 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDirectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0, verbose_name='序号')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='方向名称')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='方向描述信息')),
                ('recomment_home_hot', models.BooleanField(default=False, verbose_name='是否推荐到首页最热栏目')),
                ('recomment_home_top', models.BooleanField(default=False, verbose_name='是否推荐到首页必学栏目')),
            ],
            options={
                'verbose_name_plural': '方向',
                'db_table': 'fg_course_direction',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, db_index=True, max_length=200, null=True, verbose_name='名称')),
                ('orders', models.IntegerField(default=0, verbose_name='序号')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.SmallIntegerField(choices=[(2, '班主任'), (1, '导师'), (0, '讲师')], default=0, verbose_name='讲师身份')),
                ('title', models.CharField(max_length=100, verbose_name='职位、职称')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='导师签名')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/%Y/', verbose_name='讲师头像')),
                ('brief', models.TextField(max_length=255, verbose_name='讲师描述')),
            ],
            options={
                'verbose_name_plural': '讲师信息',
                'db_table': 'fg_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0, verbose_name='序号')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='分类名称')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='分类描述信息')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_list', to='course.coursedirectionmodel', verbose_name='方向')),
            ],
            options={
                'verbose_name_plural': '课程分类',
                'db_table': 'fg_course_category',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, db_index=True, max_length=200, null=True, verbose_name='名称')),
                ('orders', models.IntegerField(default=0, verbose_name='序号')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_cover', models.ImageField(blank=True, null=True, upload_to='course/cover/', verbose_name='封面图片')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course/video/', verbose_name='封面视频')),
                ('course_type', models.SmallIntegerField(choices=[(1, '会员专享'), (2, '学位课程'), (0, '付费购买')], default=0, verbose_name='付费课程')),
                ('level', models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=0, verbose_name='难度等级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详情介绍')),
                ('status', models.SmallIntegerField(choices=[(1, '下线'), (2, '预上线'), (0, '上线')], default=0, verbose_name='课程状态')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('period', models.IntegerField(default=7, verbose_name='建议学习周期（天）')),
                ('attachment_path', models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='课件路径')),
                ('attachment_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='课件路径')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('lessons', models.IntegerField(default=0, verbose_name='总课时数量')),
                ('pub_lessons', models.IntegerField(default=0, verbose_name='已更新的课时数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='课程价格')),
                ('credit', models.IntegerField(blank=True, default=0, null=True, verbose_name='积分兑换')),
                ('recomment_home_hot', models.BooleanField(default=False, verbose_name='是否推荐到首页最热栏目')),
                ('recomment_home_top', models.BooleanField(default=False, verbose_name='是否推荐到首页必须栏目')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='course.coursecategorymodel', verbose_name='分类')),
                ('direction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='course.coursedirectionmodel', verbose_name='方向')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_list', to='course.teachermodel', verbose_name='讲师')),
            ],
            options={
                'verbose_name_plural': '课程信息',
                'db_table': 'fg_course_info',
            },
        ),
    ]
