# Generated by Django 5.1 on 2024-09-02 08:25

import ckeditor_uploader.fields
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategorymodel',
            name='remark',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='分类描述信息'),
        ),
        migrations.AlterField(
            model_name='coursedirectionmodel',
            name='remark',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='方向描述信息'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_type',
            field=models.SmallIntegerField(choices=[(1, '会员专享'), (0, '付费购买'), (2, '学位课程')], default=0, verbose_name='付费课程'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '高级'), (0, '初级'), (1, '中级')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '预上线'), (0, '上线'), (1, '下线')], default=0, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='avatar',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='avatar/%Y/', variations={'thumb_800x800': {'height': 800, 'width': 800}}, verbose_name='讲师头像'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, verbose_name='讲师描述'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '讲师'), (2, '班主任'), (1, '导师')], default=0, verbose_name='讲师身份'),
        ),
    ]
