# Generated by Django 5.1 on 2024-09-04 08:01

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursecategorymodel_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '预上线'), (1, '下线'), (0, '上线')], default=0, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='avatar',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='avatar/%Y/', variations={'thumb_400x400': {'height': 400, 'width': 400}, 'thumb_50x50': {'height': 50, 'width': 50}, 'thumb_800x800': {'height': 800, 'width': 800}}, verbose_name='讲师头像'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(2, '班主任'), (1, '导师'), (0, '讲师')], default=0, verbose_name='讲师身份'),
        ),
    ]
