# Generated by Django 5.1 on 2024-09-05 03:40

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_activatemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatemodel',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 11, 40, 32, 401134), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activatemodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 11, 40, 32, 401134), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_type',
            field=models.SmallIntegerField(choices=[(1, '会员专享'), (0, '付费购买'), (2, '学位课程')], default=0, verbose_name='付费课程'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '中级'), (0, '初级'), (2, '高级')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '预上线'), (1, '下线'), (0, '上线')], default=0, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '讲师'), (1, '导师'), (2, '班主任')], default=0, verbose_name='讲师身份'),
        ),
        migrations.CreateModel(
            name='CourseChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, db_index=True, max_length=200, null=True, verbose_name='名称')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=1, verbose_name='第几章')),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='章节描述')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='章节发布时间')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel', verbose_name='课程')),
            ],
            options={
                'db_table': 'fg_course_chapter',
            },
        ),
        migrations.CreateModel(
            name='CourseLessonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, db_index=True, max_length=200, null=True, verbose_name='名称')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=1, verbose_name='第几节')),
                ('lesson_type', models.SmallIntegerField(choices=[(1, '练习'), (0, '文档'), (2, '视频')], default=2, verbose_name='文档类型')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='课时时长')),
                ('lesson_link', models.CharField(max_length=255, verbose_name='课时连接')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='课时发布时间')),
                ('free_trail', models.BooleanField(default=False, verbose_name='是否可以免费试看')),
                ('chapter', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_list', to='course.coursechaptermodel', verbose_name='章节')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_list', to='course.coursemodel', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '课时',
                'db_table': 'fg_course_lesson',
            },
        ),
    ]
