# Generated by Django 5.1 on 2024-09-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_activatemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatemodel',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 16, 7, 9, 853677), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activatemodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 16, 7, 9, 853677), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='courselessonsmodel',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(0, '文档'), (2, '视频'), (1, '练习')], default=2, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '付费购买'), (2, '学位课程'), (1, '会员专享')], default=0, verbose_name='付费课程'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '高级'), (0, '初级'), (1, '中级')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0, verbose_name='课程状态'),
        ),
    ]
