# Generated by Django 5.1 on 2024-09-10 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_activatemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatemodel',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 15, 41, 58, 329814), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activatemodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 15, 41, 58, 329814), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='courselessonsmodel',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(1, '练习'), (2, '视频'), (0, '文档')], default=2, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '中级'), (0, '初级'), (2, '高级')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '导师'), (0, '讲师'), (2, '班主任')], default=0, verbose_name='讲师身份'),
        ),
    ]
