# Generated by Django 4.2.16 on 2024-09-13 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_activatemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatemodel',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 17, 27, 8, 67328), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activatemodel',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 17, 27, 8, 67328), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='courselessonsmodel',
            name='lesson_type',
            field=models.SmallIntegerField(choices=[(2, '视频'), (1, '练习'), (0, '文档')], default=2, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '中级'), (0, '初级'), (2, '高级')], default=0, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '导师'), (2, '班主任'), (0, '讲师')], default=0, verbose_name='讲师身份'),
        ),
    ]
