# Generated by Django 4.2.16 on 2024-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_navmodel_postion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmodel',
            name='postion',
            field=models.ImageField(choices=[(0, '顶部导航'), (1, '底部导航')], default=0, upload_to='', verbose_name='导航位置区分'),
        ),
    ]
